StartingClass: 'Human'
StartingMagic: 10000
MagicCap: 10000
# The amount of recruiting items a player can make (Moonflower Potion, etc) -1 removes the limit
recruitingItemLimit: 1

RunnableFrequency:
  #Frequency is in ticks (1/20 of a second)
  updateMagicDisplay: 5
  NightVision: 5
  Speed: 5
  ejectIlligalArmour: 5
  immovableSpells: 5
  HostileAnimals: 20
  GrappleArrowTeleport: 5

FollowerSettings:
  # the distance required for a follower to start walking towards you
  ApproachLeaderDistance: 5
  # the distance at which a follower will stop walking towards you
  StayDistance: 3
  # the distance required for a follower to teleport to you
  TeleportDistance: 20

DonationValue:
  #Format: "Material: Value"
  #You can find the list of material names here: "https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html"
  HolyAlter:
    COOKED_CHICKEN: 6
    COOKED_COD: 5
    COOKED_MUTTON: 6
    COOKED_PORKCHOP: 8
    COOKED_RABBIT: 5
    COOKED_SALMON: 6
    BEEF: 3
    CHICKEN: 2
    COD: 2
    MUTTON: 2
    PORKCHOP: 3
    RABBIT: 3
    SALMON: 2
    ROTTEN_FLESH: 4
    COOKED_BEEF: 8
    TROPICAL_FISH: 1
    APPLE: 4
    BAKED_POTATO: 5
    BEETROOT: 1
    BEETROOT_SOUP: 6
    BREAD: 5
    CAKE: 14
    CARROT: 3
    CHORUS_FRUIT: 4
    COOKIE: 2
    DRIED_KELP: 1
    ENCHANTED_GOLDEN_APPLE: 724
    GOLDEN_APPLE: 84
    GOLDEN_CARROT: 14
    HONEY_BOTTLE: 6
    MELON_SLICE: 2
    MUSHROOM_STEW: 6
    POTATO: 1
    PUMPKIN_PIE: 8
    RABBIT_STEW: 10
    SWEET_BERRIES: 2
    GOLD_NUGGET: 1
    GOLD_INGOT: 10
    GOLD_BLOCK: 90
  UnholyAlter:
    #MATERIAL: VALUE
    BONE: 3
    ROTTEN_FLESH: 2
    MAGMA_CREAM: 5
    PHANTOM_MEMBRANE: 10
    ARROW: 2
    ENDER_PEARL: 8
    BLAZE_ROD: 5
    STRING: 1
    SPIDER_EYE: 3
    GUNPOWDER: 3
    GHAST_TEAR: 6
    SLIME_BALL: 4
    GOLD_NUGGET: 1
    GOLD_INGOT: 10
    GOLD_BLOCK: 90

Messages:
  prefix: '&f[&6Super&bnatural&f]'
  # error messages
  unknown-command: '&4Error: &cUnknown Command'
  insufficient-permission: '&4Error: &cInsufficient Permission'
  must-specify-player: '&4Error: &cNo Player Specified'
  invalid-bounty: '&4Error: &cInvalid Bounty'
  no-console: 'Error: Console cannot use this command'
  insufficient-balance: '%prefix% &cInsufficient funds'
  insufficient-magic: '%prefix% &cInsufficient Magic'
  insufficient-health: '%prefix% &cInsufficient Health'
  insufficient-hunger: '%prefix% &cInsufficient Hunger'
  target-must-be-supernatural: '%prefix% &cTarget must be in a Supernatural type Class'
  no-bounty-on-self: '%prefix% &cYou cant put a bounty on your self'
  teleport-failure: '&4Error: &cNo teleport location set!'
  # general messages
  reload-success: '%prefix% &aConfig reloaded!'
  only-supernaturals: '%prefix% &cYou can only %spellname% supernaturals'
  unknown-race: '%prefix% &cUnknown race'
  setrace-success: '%prefix% &aYou are now a %class%'
  cured-first: '%prefix% &cYou must be cured before becoming a %class%'
  already-class: '%prefix% &cYou are already a %class%'
  cooldown: '%prefix% &cThis ability is on cooldown...'
  # infection messages
  supernatural-infection-infector: '%prefix% &aYou infected %victim% with the %class% disease'
  supernatural-infection-infected: '%prefix% &aYou have been infected with the %class% disease'
  # restriction messages
  vampire-wooden-object: '%prefix% &cVampires cannot attack with Wooden Objects'
  necromancer-netherite-object: '%prefix% &cNecromancers can only attack with Netherite Objects'
  witchhunter-melee-object: '%prefix% &cWitch Hunters cannot attack with Melee Weapons'
  vampire-no-eat: '%prefix% &cVampires cannot eat food'
  night-only-abilities: '%prefix% &cYou cannot use abilities during the day'
  recruiting-item-limit: '%prefix% &cYou have reached the limit for the amount of this type of recruiting item you can make!'
  witchhunter-only-command: '%prefix% &cYou must be a Witch Hunter to use this command'
  # follower messages
  follower-follow: '%prefix% &6This follower is now following you'
  follower-wait: '%prefix% &6This follower is now waiting for you'
  # bounty messages
  no-bounty: '%prefix% &cThis player doesnt have a bounty placed on them'
  bounty-notify-sender: '%prefix% &6You put a bounty of %bounty%$ on %target% after the tax rate of %percenttax%% was subtracted from your total bounty")'
  bounty-notify-target: '%prefix% &6%player% put a bounty of %bounty%$ on you.'
  bounty-notify-all: '%prefix% &6%player% put a bounty of %bounty%$ on %target%'
  bounty-get: '%prefix% &6%target% has a bounty of %bounty%$ on them'
  redeem-bounty: '%prefix% &6You redeemed the %bounty%$ bounty placed on %target%'
  # exorcise spell messages
  exorcism-success-target: '%prefix% &aYou have been exorcised'
  exorcism-success-sender: '%prefix% &aYou successfully exorcised %target%!'
  # banish spell messages
  banishment-success-target: '%prefix% &aYou have been banished'
  banishment-success-sender: '%prefix% &aYou successfully banished %target%!'
  no-banish-location: '%prefix% &cBanish Location not set!'
  # teleport spell messages
  set-teleport-location: '%prefix% &6Teleport Location Set'
  teleport-success: '%prefix% &6Teleporting...'
  # drain spell messages
  target-no-magic: '%prefix% &cTarget has no magic'
  # Heal Human Spell messages
  full-health: '%prefix% &c%target% is already at full health'
  heal-received: '%prefix% &6You were healed by %player%'
  target-healed: '%prefix% &6Successfully healed %target%'
  # Guardian Angel messages
  guardian-angel-failed-sender: '%prefix% &c%target% already has the Guardian Angel effect applied'
  guardian-angel-failed-target: '%prefix% &c%Player% tried to give you the Guardian Angel effect but you already have it'
  guardian-angel-succeeded-sender: '%prefix% &6Guardian Angel effect applied to %target%'
  guardian-angel-succeeded-target: '%prefix% &6%Player% gave your the Guardian Angel effect'
  guardian-angel-use: '%prefix% &6The Guardian Angel Effect Saved You!'
  # Ressurection Spawn messages
  set-ressurection-location: '%prefix% &6Ressurection Location Set'
  go-ressurection-location: '%prefix% &6Teleporting to Ressurection Location'
  # alter messages
  holy-donate-only: '%prefix% &6You must be a Holy Class to donate to church'
  necromancer-donate-only: '%prefix% &6You must be a Necromancer to donate to church'
  witchhunter-use-only: '%prefix% &6You must be a Witch Hunter to use this'
  witchhunter-only-command: '%prefix% &6You must be a Witch Hunter to run this command'
  
PercentInfectionChances:
  Death-By-Supernatural: 12.5
  Death-By-Lava: 12.5
  Death-In-Nether: 10
  Death-By-Wolf: 10
  Death-By-Bat: 10
  Death-By-Monster: 10
  Eating-Rotten-Flesh: 1
  
Prefixes:
  Human: '&f[&aHuman&f]'
  Vampire: '&f[&cVampire&f]'
  Werewolf: '&f[&8Werewolf&f]'
  Ghoul: '&f[&6Ghoul&f]'
  Demon: '&f[&4Demon&f]'
  Priest: '&f[&ePriest&f]'
  Necromancer: '&f[&1Necromancer&f]'
  WitchHunter: '&f[&5Witchhunter&f]'
  Angel: '&f[&eAngel&f]'
  Shade: '&f[&7Shade&f]'
  Siren: '&f[&3Siren&f]'
  EarthElemental: '&f[&2Earth Elemental&f]'
  WaterElemental: '&f[&bWater Elemental&f]'
  FireElemental: '&f[&6Fire Elemental&f]'
 
Spells:
  Vampire:
    Teleport:
      SpellName: '&eTeleport'
      Description: '&eTeleports you to a set location'
      IconMaterial: 'PAPER'
      Magic-Cost: 9000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    SetTeleportLocation:
      SpellName: '&eSet Teleport Location'
      Description: '&eSets the location you will teleport to when using Teleport'
      IconMaterial: 'PAPER'
      Magic-Cost: 0
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'left'
    HighJump:
      SpellName: '&eHigh Jump'
      Description: '&eLaunches you into the air'
      IconMaterial: 'FEATHER'
      Magic-Cost: 1000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Bloodvial:
      SpellName: '&eBlood Vial'
      Description: '&eStores some of your hunger in a consumable potion'
      IconMaterial: 'FERMENTED_SPIDER_EYE'
      Magic-Cost: 500
      Food-Cost: 3
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    ToggleRegenerationEnabled:
      SpellName: '&eToggle Regeneration - Enabled'
      Description: '&eConsumes 200 Magika / Heart'
      IconMaterial: 'APPLE'
      Magic-Cost: 0
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    ToggleRegenerationDisabled:
      SpellName: '&eToggle Regeneration - Disabled'
      Description: '&eConsumes 200 Magika / Heart'
      IconMaterial: 'APPLE'
      Magic-Cost: 0
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    ToggleWaterBreathingEnabled:
      SpellName: '&eToggle Water Breathing - Enabled'
      Description: '&eConsumes 30 Magika / Second'
      IconMaterial: 'LILY_PAD'
      Magic-Cost: 0
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    ToggleWaterBreathingDisabled:
      SpellName: '&eToggle Water Breathing - Disabled'
      Description: '&eConsumes 30 Magika / Second'
      IconMaterial: 'LILY_PAD'
      Magic-Cost: 0
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Regeneration:
      #Regenerates 1 Heart
      #Cost Per Frequency
      Magic-Cost: 200
      Food-Cost: 0
      Health-Cost: 0
      #Frequency In Ticks
      Frequency: 20
    WaterBreathing:
      #Regenerates 1 Heart
      #Cost Per Frequency
      Magic-Cost: 30
      Food-Cost: 0
      Health-Cost: 0
      #Frequency In Ticks
      Frequency: 20
    Bloodrose:
      SpellName: '&eCreate Bloodrose Potion'
      Description: '&eCreates a concoction that when consumed turns the consumer into a Vampire'
      IconMaterial: 'POPPY'
      Magic-Cost: 10000
      Food-Cost: 0
      Health-Cost: 10
      Cooldown: 0
      TriggerMethod: 'right'
  Werewolf:
    SummonWolf:
      SpellName: '&eSummon Wolf'
      Description: '&eSummons a Wolf Follower'
      IconMaterial: 'BONE'
      Magic-Cost: 4000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Dash:
      SpellName: '&eDash'
      Description: '&eLaunches you forward'
      IconMaterial: 'FEATHER'
      Magic-Cost: 400
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Moonflower:
      SpellName: '&eCreate Moonflower Potion'
      Description: '&eCreates a concoction that when consumed turns the consumer into a Werewolf'
      IconMaterial: 'BLUE_ORCHID'
      Magic-Cost: 10000
      Food-Cost: 0
      Health-Cost: 10
      Cooldown: 0
      TriggerMethod: 'right'
  Ghoul:
    SummonMonster:
      SpellName: '&eSummon Monster'
      Description: '&eSummons a Random Monster'
      IconMaterial: 'BONE_MEAL'
      Magic-Cost: 1000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    UnholyBond:
      SpellName: '&eUnholy Bond'
      Description: '&eDeals damage to the target whenever they hit the caster for the next 2 1/2 Minuites'
      IconMaterial: 'BONE'
      Magic-Cost: 5000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'hit'
    Ghoulish:
      SpellName: '&eCreate Ghoulish Potion'
      Description: '&eCreates a concoction that when consumed turns the consumer into a Ghoul'
      IconMaterial: 'WITHER_ROSE'
      Magic-Cost: 10000
      Food-Cost: 0
      Health-Cost: 10
      Cooldown: 0
      TriggerMethod: 'right'
  Demon:
    Fireball:
      SpellName: '&eFireball'
      Description: '&eLaunches a Fireball wherever the player is looking'
      IconMaterial: 'REDSTONE'
      Magic-Cost: 2000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Explosion:
      SpellName: '&eExplosion'
      Description: '&eExplodes the area around the player'
      IconMaterial: 'TNT'
      Magic-Cost: 8000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Snare:
      SpellName: '&eSnare'
      Description: '&ePrevents the target from moving for 10 seconds'
      IconMaterial: 'INK_SAC'
      Magic-Cost: 1000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'hit'
    SummonStrider:
      SpellName: '&eSummon Strider'
      Description: '&eSpawns a Strider that the player can ride across lava lakes'
      IconMaterial: 'WARPED_FUNGUS_ON_A_STICK'
      Magic-Cost: 2500
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Hellish:
      SpellName: '&eHellish'
      Description: '&eCreates a concoction that when consumed turns the consumer into a Demon'
      IconMaterial: 'NETHER_WART'
      Magic-Cost: 10000
      Food-Cost: 0
      Health-Cost: 10
      Cooldown: 0
      TriggerMethod: 'right'
  Priest:
    Banish:
      SpellName: '&eBanish'
      Description: '&eSends the target to the banish location'
      IconMaterial: 'IRON_BARS'
      Magic-Cost: 4000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
      Range: 20
    Exorcise:
      SpellName: '&eExorcise'
      Description: '&eTurns the target back into a human'
      IconMaterial: 'FLINT_AND_STEEL'
      Magic-Cost: 9000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
      Range: 20
    Drain:
      SpellName: '&eDrain'
      Description: '&eDrains 15% of the targets magic'
      IconMaterial: 'STICK'
      Magic-Cost: 1000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
      Range: 20
    HealHuman:
      SpellName: '&eHeal Human'
      Description: '&eIncreases the targets health by 0-5 hearts'
      IconMaterial: 'PAPER'
      Magic-Cost: 1000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'hit'
    GuardianAngel:
      SpellName: '&eGuardian Angel'
      Description: '&eNext time the target is about to die they will be given a second chance'
      IconMaterial: 'WHITE_WOOL'
      Magic-Cost: 5000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'hit'
    Cure:
      SpellName: '&eCure'
      Description: '&eCreates a concoction that when consumed turns the consumer into a Human'
      IconMaterial: 'BAMBOO'
      Magic-Cost: 5000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    HolyBook:
      SpellName: '&eHoly Book'
      Description: '&eCreates a book that when read turns the reader into a Priest'
      IconMaterial: 'BOOK'
      Magic-Cost: 10000
      Food-Cost: 0
      Health-Cost: 10
      Cooldown: 0
      TriggerMethod: 'right'
  Necromancer:
    SummonSkeleton:
      SpellName: '&eSummon Skeleton'
      Description: '&eSummons a Skeleton Follower'
      IconMaterial: 'BONE'
      Magic-Cost: 1000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    SummonUndead:
      SpellName: '&eSummon Undead'
      Description: '&eSummons a random Undead Follower'
      IconMaterial: 'ROTTEN_FLESH'
      Magic-Cost: 5000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    HealUndead:
      SpellName: '&eHeal Undead'
      Description: '&eHeals nearby Undead'
      IconMaterial: 'RED_DYE'
      Magic-Cost: 3500
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    SetRessurectionSpawn:
      SpellName: '&eSet Resurection Spawn'
      Description: '&eSets next respawn locations'
      IconMaterial: 'BONE_MEAL'
      Magic-Cost: 4000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    BookOfDeath:
      SpellName: '&eBook of Death'
      Description: '&eCreates a book that when read turns the reader into a Necromancer'
      IconMaterial: 'BOOK'
      Magic-Cost: 10000
      Food-Cost: 0
      Health-Cost: 10
      Cooldown: 0
      TriggerMethod: 'right'
  WitchHunter:
    ArrowSwitcher:
      SpellName: '&eArrow Switcher'
      Description: '&eSwitches between arrow types'
      IconMaterial: 'BOW'
      Magic-Cost: 0
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'left'
    TripleArrow:
      SpellName: '&eTriple Arrow'
      Description: '&eFires 3 arrows next to eachother'
      IconMaterial: 'BOW'
      Magic-Cost: 300
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'shoot'
    GrappleArrow:
      SpellName: '&eGrapple Arrow'
      Description: '&ePulls you to wherever your arrow lands'
      IconMaterial: 'BOW'
      Magic-Cost: 500
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'shoot'
    FireArrow:
      SpellName: '&eFire Arrow'
      Description: '&eSets whatever you hit on fire'
      IconMaterial: 'BOW'
      Magic-Cost: 500
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'shoot'
    PowerArrow:
      SpellName: '&ePower Arrow'
      Description: '&eCauses an explosion'
      IconMaterial: 'BOW'
      Magic-Cost: 500
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 80
      TriggerMethod: 'shoot'
    VolleyArrow:
      SpellName: '&eVolley Arrow'
      Description: &eShoots multiple consecutive arrows''
      IconMaterial: 'BOW'
      Magic-Cost: 300
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 80
      TriggerMethod: 'shoot'
    BookOfWitchHunter:
      SpellName: '&eCreate Book of the Witch Hunter'
      Description: ''
      IconMaterial: 'BOOK'
      Magic-Cost: 10000
      Food-Cost: 0
      Health-Cost: 10
      Cooldown: 0
      TriggerMethod: 'right'
  Angel:
    HolySmite:
      SpellName: '&eHoly Smite'
      Description: '&eSpell WIP'
      IconMaterial: 'BONE_MEAL'
      Magic-Cost: 1000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Taunt:
      SpellName: '&eTaunt'
      Description: '&eSpell WIP'
      IconMaterial: 'LEAD'
      Magic-Cost: 6000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    HolyBlessing:
      SpellName: '&eHoly Blessing'
      Description: '&eSpell WIP'
      IconMaterial: 'DANDELION'
      Magic-Cost: 3000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'
    Wings:
      SpellName: '&eWings'
      Description: '&eMakes the caster glide for the next 20 seconds'
      IconMaterial: 'FEATHER'
      Magic-Cost: 5000
      Food-Cost: 0
      Health-Cost: 0
      Cooldown: 0
      TriggerMethod: 'right'